# --------------------------------------------------------------  
# (C)Copyright 2001,2006,                                         
# International Business Machines Corporation,                    
# Sony Computer Entertainment, Incorporated,                      
# Toshiba Corporation,                                            
#                                                                 
# All Rights Reserved.                                            
# --------------------------------------------------------------  
# PROLOG END TAG zYx                                              

########################################################################
#			Target
########################################################################

DIRS = spu ppu 

########################################################################
#			make.footer
########################################################################

include /opt/cell/sdk/buildutils/make.footer

#ifdef CELL_TOP
#	include $(CELL_TOP)/make.footer
#else
#	include /opt/ibm/cell-sdk/prototype/make.footer
#endif
